"""add user password

Revision ID: 4f4cf4a4af41
Revises: bdfe78523595
Create Date: 2025-08-08 18:57:45.253249

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f4cf4a4af41"
down_revision: Union[str, Sequence[str], None] = "bdfe78523595"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_admin", sa.Boolean(), nullable=False))
    op.add_column("users", sa.Column("password", sa.String(length=100), nullable=False))
    op.drop_column("users", "bio")
    op.drop_column("users", "is_active")
    op.drop_column("users", "full_name")
    op.drop_column("users", "created_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("created_at", sa.VARCHAR(), nullable=True))
    op.add_column(
        "users", sa.Column("full_name", sa.VARCHAR(length=100), nullable=True)
    )
    op.add_column("users", sa.Column("is_active", sa.BOOLEAN(), nullable=False))
    op.add_column("users", sa.Column("bio", sa.TEXT(), nullable=True))
    op.drop_column("users", "password")
    op.drop_column("users", "is_admin")
    # ### end Alembic commands ###
