"""add model user_tg

Revision ID: 86f8069ffe34
Revises: 737ab3912d7c
Create Date: 2025-12-11 19:46:33.024411

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "86f8069ffe34"
down_revision: Union[str, Sequence[str], None] = "737ab3912d7c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users_in_telegram",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tg_code", sa.String(length=25), nullable=False),
        sa.Column("user_tg_id", sa.String(length=255), nullable=True),
        sa.Column("user_in_site", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_in_site"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users_in_telegram")
    # ### end Alembic commands ###
